### ISSUE TITLE
Query条件に「NOT EQUALS」が欲しいです

### ISSUE THREAD

**Issue by HillTopTRPG** [esnya/nekostore#7]
毎度大変お世話になっています。
タイトルの通りなのですが、'!=' か '<>' の指定が欲しいです。
https://github.com/esnya/nekostore/blob/c2b8f7571208228b05f26570434f7f122936dc4f/src/driver/basic/impl/BasicQuery.ts#L15-L21

**Comment by esnya** [comment]
Firestoreの制約上でそれらのクエリは使えなくなっています。「バックエンドを選ばずに使える」ためにバックエンド固有の機能を入れることはできる限り避ける方針です。

参考：https://stackoverflow.com/questions/47251919/firestore-how-to-perform-a-query-with-inequality-not-equals

**Comment by HillTopTRPG** [comment]
ご解答ありがとうございますっ！
その仕様に合わせて考えようと思います！
